### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by dalu93** [jmfieldman/Brisk#5]
Hi,
Thanks for this great library, I was looking for something like this for so much time.
I'd like to  report that the object that is using Brisk is not deallocated until the `completion` is called.

Take for example the code below

```swift
import UIKit
import Brisk

class AViewController: UIViewController {
    
    var presentedOnce = false
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        guard presentedOnce == false else { return }
        presentedOnce = true
        
        let controller = ViewController()
        present(controller, animated: true) {
            self.dismiss(animated: true, completion: nil)
        }
    }
}

class ViewController: UIViewController {
    
    let viewModel = ViewModel()

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        print("Starting")
        
        let result = <<+{ [weak self] in self?.viewModel.getTodos(completionHandler: $0) }
        switch result {
        case .success(let todos):
            print(String(describing: todos))
        default: break
        }
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    deinit {
        print("deinit")
    }
}

class ViewModel {
    
    func getTodos(completionHandler: @escaping (Result<[Todo], Error>) -> ()) {
        DispatchQueue.main.asyncAfter(deadline: .now() + 5) {
            let todo = Todo(id: "a", content: "sdif")
            completionHandler(.success([todo, todo]))
        }
    }
}

struct Todo {
    let id: String
    let content: String
}

enum Result<Value, ErrorType> {
    case success(Value)
    case failed(ErrorType)
}
```

I'm expecting the `deinit` print is printed right after the viewController is dismissed, but not, it's printed only right after the `result` is returned by the Brisk block.

Is there any workaround to get rid of this issue quickly?

**Comment by jmfieldman** [comment]
Hi Luca, glad you like the library!

On my first reading of the code, my interpretation of what is happening is that you're expecting the instance of ```ViewController``` to deallocate because the block: ```{ [weak self] in self?.viewModel.getTodos(completionHandler: $0) }``` has a weak reference?

There are a few things to consider:

Because you're using the ```<<+``` operator, the block in question is called asynchronously on the main thread, but this is because it will spin on the main thread itself while continuing to process events on the main run loop until ```completionHandler``` is called.  

So while it is true that the block will be called on the "next" cycle through the main loop, your ViewController's ```viewDidLoad``` method is still in the middle of executing (waiting for the ```completionHandler```), and thus your ```ViewController``` instance will continue have a reference to it (from the event that called ```viewDidLoad``` in the first place).

I guess one general rule is: *if you're inside an object's method, you know it has at least one reference from the place that method was originally called from.*  So when result is finally processed and ```viewDidLoad``` completes, that reference is released and you get the ```deinit```.

----

So let's take a step back and see how to resolve the problem.  Fundamentally, you need viewDidLoad (and any function called on the main thread) to complete its execution immediately.  Brisk is not a magic bullet that allows you to violate that principal.  

If you want to use the ```<<+``` operator, you'll have to redirect it to another cycle of the main queue.  Your viewDidLoad would look something like this:

```swift
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        // capture the view model here before we start
        let myModel = self.viewModel

        DispatchQueue.main.async { [weak self] in
            // This is called on the main queue in a separate cycle of the run loop
            // so viewDidLoad has finished by now
        
            // You cannot have optionals inside the brisk block, since it must be
            // guaranteed to call the completionHandler.  That's why we capture
            // a non-optional viewModel before
            let result = <<+{ myModel.getTodos(completionHandler: $0) }
            switch result {
            case .success(let todos):
                print(String(describing: todos))
                self?.doSomethingWith(todos: todos)
            default: break
            }
        }
    }
```

I'll be honest though.. even in this situation I'm not sure if the [weak self] will resolve to nil by the time it is used -- not sure if it gets evaluated when the block enters and then keeps its reference through the lifetime of the block, or if it can be set to nil by ARC mid-block.
